name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn clean package -DskipTests
      
    - name: Run Tests
      run: mvn test
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/clicknbuy:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/clicknbuy:${{ github.sha }}
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/clicknbuy:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/clicknbuy:buildcache,mode=max

    - name: Update deployment status
      run: |
        echo "🎉 Deployment completed successfully!"
        echo "Docker image: ${{ secrets.DOCKERHUB_USERNAME }}/clicknbuy:${{ github.sha }}"